name: Cypress Tests

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

  # Run automatically every day at 3:45 PM Lebanon time (13:45 UTC)
  schedule:
    - cron: "45 13 * * *"

  # Allow manual trigger from GitHub UI
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies inside the FDTraining folder
      - name: Install dependencies
        run: |
          cd FDTraining
          npm install

      # Run Cypress using official action
      - name: Run Cypress using official action
        uses: cypress-io/github-action@v6
        with:
          working-directory: FDTraining
          runTests: true
